### PR TITLE
Prepare for OTP 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
(compilation-wise, at least)

This became apparent after https://github.com/erlang/otp/pull/2735.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@mpitid: it seems your default branch is `dev` but that one's a bit outdated. Is this expected?

**Comment by paulo-ferraz-oliveira** [comment]
Bump.

**Comment by paulo-ferraz-oliveira** [comment]
Bump.

**Comment by mpitid** [comment]
Thanks, will review and also see about getting master and dev in sync (and probably dropping dev eventually).

**Comment by paulo-ferraz-oliveira** [comment]
This doesn't seem to move. May re-open if I get around to it, but for the time being I have no time for this.

**Pull request closed without merging**
